/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_biglybt_platform_win32_access_impl_AEWin32AccessInterface */

#ifndef _Included_com_biglybt_platform_win32_access_impl_AEWin32AccessInterface
#define _Included_com_biglybt_platform_win32_access_impl_AEWin32AccessInterface
#ifdef __cplusplus
extern "C" {
#endif
#undef com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_HKEY_CLASSES_ROOT
#define com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_HKEY_CLASSES_ROOT 1L
#undef com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_HKEY_CURRENT_CONFIG
#define com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_HKEY_CURRENT_CONFIG 2L
#undef com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_HKEY_LOCAL_MACHINE
#define com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_HKEY_LOCAL_MACHINE 3L
#undef com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_HKEY_CURRENT_USER
#define com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_HKEY_CURRENT_USER 4L
#undef com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_WM_QUERYENDSESSION
#define com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_WM_QUERYENDSESSION 17L
#undef com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_WM_ENDSESSION
#define com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_WM_ENDSESSION 22L
#undef com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_WM_POWERBROADCAST
#define com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_WM_POWERBROADCAST 536L
#undef com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_PBT_APMQUERYSUSPEND
#define com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_PBT_APMQUERYSUSPEND 0L
#undef com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_PBT_APMSUSPEND
#define com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_PBT_APMSUSPEND 4L
#undef com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_PBT_APMRESUMESUSPEND
#define com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_PBT_APMRESUMESUSPEND 7L
#undef com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_BROADCAST_QUERY_DENY
#define com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_BROADCAST_QUERY_DENY 1112363332i64
#undef com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_ES_SYSTEM_REQUIRED
#define com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_ES_SYSTEM_REQUIRED 1L
#undef com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_ES_DISPLAY_REQUIRED
#define com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_ES_DISPLAY_REQUIRED 2L
#undef com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_ES_USER_PRESENT
#define com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_ES_USER_PRESENT 4L
#undef com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_ES_AWAYMODE_REQUIRED
#define com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_ES_AWAYMODE_REQUIRED 64L
#undef com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_ES_CONTINUOUS
#define com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_ES_CONTINUOUS -2147483648L
/*
 * Class:     com_biglybt_platform_win32_access_impl_AEWin32AccessInterface
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_initialise
  (JNIEnv *, jclass);

/*
 * Class:     com_biglybt_platform_win32_access_impl_AEWin32AccessInterface
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_getVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_biglybt_platform_win32_access_impl_AEWin32AccessInterface
 * Method:    readStringValue
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_readStringValue
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     com_biglybt_platform_win32_access_impl_AEWin32AccessInterface
 * Method:    writeStringValue
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_writeStringValue
  (JNIEnv *, jclass, jint, jstring, jstring, jstring);

/*
 * Class:     com_biglybt_platform_win32_access_impl_AEWin32AccessInterface
 * Method:    readWordValue
 * Signature: (ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_readWordValue
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     com_biglybt_platform_win32_access_impl_AEWin32AccessInterface
 * Method:    writeWordValue
 * Signature: (ILjava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_writeWordValue
  (JNIEnv *, jclass, jint, jstring, jstring, jint);

/*
 * Class:     com_biglybt_platform_win32_access_impl_AEWin32AccessInterface
 * Method:    deleteKey
 * Signature: (ILjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_deleteKey
  (JNIEnv *, jclass, jint, jstring, jboolean);

/*
 * Class:     com_biglybt_platform_win32_access_impl_AEWin32AccessInterface
 * Method:    deleteValue
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_deleteValue
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     com_biglybt_platform_win32_access_impl_AEWin32AccessInterface
 * Method:    createProcess
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_createProcess
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     com_biglybt_platform_win32_access_impl_AEWin32AccessInterface
 * Method:    moveToRecycleBin
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_moveToRecycleBin
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_biglybt_platform_win32_access_impl_AEWin32AccessInterface
 * Method:    copyPermission
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_copyPermission
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_biglybt_platform_win32_access_impl_AEWin32AccessInterface
 * Method:    testNativeAvailability
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_testNativeAvailability
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_biglybt_platform_win32_access_impl_AEWin32AccessInterface
 * Method:    traceRoute
 * Signature: (IIIILcom/biglybt/platform/win32/access/impl/AEWin32AccessCallback;)V
 */
JNIEXPORT void JNICALL Java_com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_traceRoute
  (JNIEnv *, jclass, jint, jint, jint, jint, jobject);

/*
 * Class:     com_biglybt_platform_win32_access_impl_AEWin32AccessInterface
 * Method:    shellExecute
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_shellExecute
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jint);

/*
 * Class:     com_biglybt_platform_win32_access_impl_AEWin32AccessInterface
 * Method:    shellExecuteAndWait
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_shellExecuteAndWait
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_biglybt_platform_win32_access_impl_AEWin32AccessInterface
 * Method:    getAvailableDrives
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_getAvailableDrives
  (JNIEnv *, jclass);

/*
 * Class:     com_biglybt_platform_win32_access_impl_AEWin32AccessInterface
 * Method:    getDriveInfo
 * Signature: (C)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_getDriveInfo
  (JNIEnv *, jclass, jchar);

/*
 * Class:     com_biglybt_platform_win32_access_impl_AEWin32AccessInterface
 * Method:    setThreadExecutionState
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_biglybt_platform_win32_access_impl_AEWin32AccessInterface_setThreadExecutionState
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
