/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class com_biglybt_platform_macosx_access_jnilib_OSXAccess */

#ifndef _Included_com_biglybt_platform_macosx_access_jnilib_OSXAccess
#define _Included_com_biglybt_platform_macosx_access_jnilib_OSXAccess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_biglybt_platform_macosx_access_jnilib_OSXAccess
 * Method:    AEGetParamDesc
 * Signature: (IIILjava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_biglybt_platform_macosx_access_jnilib_OSXAccess_AEGetParamDesc
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     com_biglybt_platform_macosx_access_jnilib_OSXAccess
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_biglybt_platform_macosx_access_jnilib_OSXAccess_getVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_biglybt_platform_macosx_access_jnilib_OSXAccess
 * Method:    getDocDir
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_biglybt_platform_macosx_access_jnilib_OSXAccess_getDocDir
  (JNIEnv *, jclass);

/*
 * Class:     com_biglybt_platform_macosx_access_jnilib_OSXAccess
 * Method:    memmove
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_com_biglybt_platform_macosx_access_jnilib_OSXAccess_memmove
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     com_biglybt_platform_macosx_access_jnilib_OSXAccess
 * Method:    initializeDriveDetection
 * Signature: (Lcom/biglybt/platform/macosx/access/jnilib/OSXDriveDetectListener;)V
 */
JNIEXPORT void JNICALL Java_com_biglybt_platform_macosx_access_jnilib_OSXAccess_initializeDriveDetection
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_biglybt_platform_macosx_access_jnilib_OSXAccess
 * Method:    initializeLight
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_biglybt_platform_macosx_access_jnilib_OSXAccess_initializeLight
  (JNIEnv *, jclass);

/*
 * Class:     com_biglybt_platform_macosx_access_jnilib_OSXAccess
 * Method:    setDefaultAppForExt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_biglybt_platform_macosx_access_jnilib_OSXAccess_setDefaultAppForExt
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_biglybt_platform_macosx_access_jnilib_OSXAccess
 * Method:    setDefaultAppForMime
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_biglybt_platform_macosx_access_jnilib_OSXAccess_setDefaultAppForMime
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_biglybt_platform_macosx_access_jnilib_OSXAccess
 * Method:    setDefaultAppForScheme
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_biglybt_platform_macosx_access_jnilib_OSXAccess_setDefaultAppForScheme
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_biglybt_platform_macosx_access_jnilib_OSXAccess
 * Method:    getDefaultAppForExt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_biglybt_platform_macosx_access_jnilib_OSXAccess_getDefaultAppForExt
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_biglybt_platform_macosx_access_jnilib_OSXAccess
 * Method:    getDefaultAppForMime
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_biglybt_platform_macosx_access_jnilib_OSXAccess_getDefaultAppForMime
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_biglybt_platform_macosx_access_jnilib_OSXAccess
 * Method:    getDefaultAppForScheme
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_biglybt_platform_macosx_access_jnilib_OSXAccess_getDefaultAppForScheme
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_biglybt_platform_macosx_access_jnilib_OSXAccess
 * Method:    canSetDefaultApp
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_biglybt_platform_macosx_access_jnilib_OSXAccess_canSetDefaultApp
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
