#!/usr/bin/env bash
# This file installs the .desktop file into your Desktop Environment
# Should be able to run as user as sudo (sudo will install it globally)

if [ -x "$(command -v desktop-file-install)" ]; then
  desktop-file-install biglybt.desktop
fi
if [ -x "$(command -v xdg-desktop-menu)" ]; then
  xdg-desktop-menu install --novendor biglybt.desktop
fi

exit 0