#!/usr/bin/env bash
# This file removed the .desktop file registration from your Desktop Environment

if [ -x "$(command -v xdg-desktop-menu)" ]; then
  xdg-desktop-menu uninstall --novendor biglybt.desktop
fi

if [ -f /usr/share/applications/biglybt.desktop ]; then
	# probably won't work unless sudo
  rm "/usr/share/applications/biglybt.desktop"
fi

exit 0